"""Single-source-of-truth hyperparameters for every figure / sweep
script that injects numbers into the manuscript.

Centralising these here is the manuscript's no-hardcode rule made
mechanical: scripts (`scripts/generate_figures.py`,
`scripts/parameter_sweep.py`, `scripts/simulate_pymdp.py`) read the
constants below, and `scripts/manuscript_variables.py` mirrors the
same constants into `output/data/manuscript_variables.json` so the
manuscript can `[[VAR:...]]` substitute them with no risk of drift.

All constants are immutable at import time.  Any change here
re-flows through every figure caption, prose value, and the
range-validation layer in `validate_manuscript.py`.

Import from this module only — domain splits live in
``hyperparameters_{grids,pymdp,robustness,experiments,sentinels}``.
"""

from __future__ import annotations

from lean.phase_constants import PHASE_LAMBDA_C1, PHASE_LAMBDA_C2  # noqa: F401 - re-export
from simulation.hyperparameters_experiments import (
    ADVERSARIAL_DEFAULT_SEED,
    ADVERSARIAL_EPSILON_GRID,
    ADVERSARIAL_LAMBDA_GRID,
    BTAI_DEFAULT_BUDGETS,
    BTAI_ENSEMBLE_COUPLING_AMPLITUDE,
    BTAI_ENSEMBLE_PREFERENCE_STRENGTH,
    BTAI_HORIZON,
    BTAI_NUM_STREAMS,
    BTAI_REFERENCE_LAMBDA,
    BTAI_UCB_EXPLORATION,
    PYMDP_AGENT_ACTION_SELECTION,
    PYMDP_AGENT_ALPHA,
    PYMDP_AGENT_INFERENCE_ALGO,
    PYMDP_AGENT_NUM_ITER,
    PYMDP_AGENT_POLICY_LEN,
    PYMDP_AGENT_USE_PARAM_INFO_GAIN,
    PYMDP_AGENT_USE_STATES_INFO_GAIN,
    REVERTIBILITY_KL_IDENTITY_TOLERANCE,
    REVERTIBILITY_LAMBDAS,
    REVERTIBILITY_TOLERANCE,
)
from simulation.hyperparameters_grids import (
    COUPLING_TAX_LAMBDAS,
    FIGURE_GLOBAL_SEED,
    KL_GEODESIC_LAMBDAS,
    LAMBDA_STAR_GAMMAS,
    LAMBDA_STAR_UTILITIES,
    LOG_WEIGHT_FLOW_LAMBDAS,
    OPTIMAL_LAMBDA_DELTAS,
    PARAMETER_SWEEP_LAMBDAS,
    PHASE_DIAGRAM_LAMBDAS,
    PHASE_LANDSCAPE_LAMBDAS,
    PHASE_LANDSCAPE_UTILITIES,
    SCHMIDT_RANK_LAMBDAS,
    FigureGrid,
)
from simulation.hyperparameters_pymdp import (
    LONG_HORIZON_DIAGNOSTIC_THRESHOLDS,
    LONG_HORIZON_LAMBDA,
    LONG_HORIZON_REPLICATE_SEEDS,
    LONG_HORIZON_SEED,
    LONG_HORIZON_STEADY_STATE_TOL,
    LONG_HORIZON_STEPS,
    LONG_HORIZON_TAIL_WINDOW,
    MULTI_K_SENTINEL_LAMBDA,
    MULTI_K_SWEEP_LAMBDAS,
    MULTI_K_VALUES,
    PYMDP_ENSEMBLE_COUPLING_LAMBDA,
    PYMDP_ENSEMBLE_GAMMA,
    PYMDP_ENSEMBLE_K,
    PYMDP_ROLLOUT_LAMBDA,
    PYMDP_ROLLOUT_SEED,
    PYMDP_ROLLOUT_STEPS,
    PYMDP_SWEEP_LAMBDAS,
    PYMDP_SWEEP_OBSERVATIONS,
)
from simulation.hyperparameters_robustness import (
    COUPLING_ABLATION_KC_MATRIX,
    COUPLING_ABLATION_VARIANTS,
    ROBUSTNESS_COUPLING_SCALES,
    ROBUSTNESS_GAMMAS,
    ROBUSTNESS_INTERACTION_FAMILIES,
    ROBUSTNESS_OBSERVATION_CONTEXTS,
    ROBUSTNESS_PREFERENCE_STRENGTHS,
    ROBUSTNESS_SWEEP_LAMBDAS,
)
from simulation.hyperparameters_sentinels import (
    ARCHETYPE_DENDROGRAM_LAMBDA,
    BERNOULLI_VERIFICATION_LAMBDAS,
    BERNOULLI_VERIFICATION_TOLERANCE,
    COUPLING_GRAPH_STREAM_COUNT,
    COUPLING_TAX_PROBE_LAMBDA,
    ISING_ALIGNMENT_SENTINEL_LAMBDAS,
    ISING_MI_SATURATION_LAMBDA,
    ISING_MI_SENTINEL_LAMBDAS,
    JOINT_HEATMAP_LAMBDA,
    MONTECARLO_MI_BIAS_TOL,
    MONTECARLO_MI_LAMBDA,
    MONTECARLO_MI_N,
    MONTECARLO_MI_SEEDS,
    MOTOR_ATTENTION_SENTINEL_LAMBDAS,
    OPTIMAL_LAMBDA_SENTINEL_DELTAS,
    PARAMETER_SWEEP_AGREEMENT_TOLERANCE,
    PARAMETER_SWEEP_DEFAULT_UTILITIES,
    PYMDP_COUPLING_ZERO_TOLERANCE,
    PYMDP_DECOMPOSITION_RESIDUAL_TOLERANCE,
    PYMDP_ENTROPY_ADD_TOLERANCE,
    PYMDP_MARGINAL_AGREEMENT_TOLERANCE,
    PYMDP_SINGLE_STREAM_FLOAT_TOLERANCE,
    PYMDP_TC_ZERO_TOLERANCE,
    PYMDP_TOTAL_CORRELATION_SENTINEL_LAMBDAS,
    SPECTRAL_RANK_ATOL,
    SPECTRAL_SENTINEL_LAMBDAS,
    TT_RANK_PROFILE_LAMBDA,
    TT_RANK_STREAM_COUNTS,
)


def grid_count(grid: FigureGrid) -> int:
    """Return ``grid.num`` — convenience for manuscript variable export."""
    return int(grid.num)


def figure_hyperparameter_summary() -> dict[str, object]:
    """Flat dict of every grid count + scalar.

    Consumed by `scripts/manuscript_variables.py` to populate the
    `[[VAR:...]]` namespace; the keys are stable and used directly
    inside `manuscript/*.md`.
    """
    return {
        # grid sizes
        "param_sweep_grid_points": grid_count(PARAMETER_SWEEP_LAMBDAS),
        "param_sweep_lambda_min": float(PARAMETER_SWEEP_LAMBDAS.start),
        "param_sweep_lambda_max": float(PARAMETER_SWEEP_LAMBDAS.stop),
        "coupling_tax_grid_points": grid_count(COUPLING_TAX_LAMBDAS),
        "coupling_tax_lambda_min": float(COUPLING_TAX_LAMBDAS.start),
        "coupling_tax_lambda_max": float(COUPLING_TAX_LAMBDAS.stop),
        "phase_diagram_grid_points": grid_count(PHASE_DIAGRAM_LAMBDAS),
        "phase_diagram_lambda_min": float(PHASE_DIAGRAM_LAMBDAS.start),
        "phase_diagram_lambda_max": float(PHASE_DIAGRAM_LAMBDAS.stop),
        "optimal_lambda_grid_points": grid_count(OPTIMAL_LAMBDA_DELTAS),
        "optimal_lambda_delta_min": float(OPTIMAL_LAMBDA_DELTAS.start),
        "optimal_lambda_delta_max": float(OPTIMAL_LAMBDA_DELTAS.stop),
        "schmidt_rank_grid_points": grid_count(SCHMIDT_RANK_LAMBDAS),
        "schmidt_rank_lambda_min": float(SCHMIDT_RANK_LAMBDAS.start),
        "schmidt_rank_lambda_max": float(SCHMIDT_RANK_LAMBDAS.stop),
        "phase_landscape_lambda_points": grid_count(PHASE_LANDSCAPE_LAMBDAS),
        "phase_landscape_lambda_min": float(PHASE_LANDSCAPE_LAMBDAS.start),
        "phase_landscape_lambda_max": float(PHASE_LANDSCAPE_LAMBDAS.stop),
        "phase_landscape_utility_points": grid_count(PHASE_LANDSCAPE_UTILITIES),
        "phase_landscape_utility_min": float(PHASE_LANDSCAPE_UTILITIES.start),
        "phase_landscape_utility_max": float(PHASE_LANDSCAPE_UTILITIES.stop),
        "log_weight_flow_grid_points": grid_count(LOG_WEIGHT_FLOW_LAMBDAS),
        "log_weight_flow_lambda_min": float(LOG_WEIGHT_FLOW_LAMBDAS.start),
        "log_weight_flow_lambda_max": float(LOG_WEIGHT_FLOW_LAMBDAS.stop),
        "kl_geodesic_grid_points": grid_count(KL_GEODESIC_LAMBDAS),
        "kl_geodesic_lambda_min": float(KL_GEODESIC_LAMBDAS.start),
        "kl_geodesic_lambda_max": float(KL_GEODESIC_LAMBDAS.stop),
        "lambda_star_utility_points": grid_count(LAMBDA_STAR_UTILITIES),
        "lambda_star_utility_min": float(LAMBDA_STAR_UTILITIES.start),
        "lambda_star_utility_max": float(LAMBDA_STAR_UTILITIES.stop),
        "lambda_star_gamma_points": grid_count(LAMBDA_STAR_GAMMAS),
        "lambda_star_gamma_min": float(LAMBDA_STAR_GAMMAS.start),
        "lambda_star_gamma_max": float(LAMBDA_STAR_GAMMAS.stop),
        # pymdp
        "pymdp_sweep_grid_points": grid_count(PYMDP_SWEEP_LAMBDAS),
        "pymdp_sweep_lambda_min": float(PYMDP_SWEEP_LAMBDAS.start),
        "pymdp_sweep_lambda_max": float(PYMDP_SWEEP_LAMBDAS.stop),
        "pymdp_rollout_steps": int(PYMDP_ROLLOUT_STEPS),
        "pymdp_rollout_seed": int(PYMDP_ROLLOUT_SEED),
        "pymdp_rollout_lambda": float(PYMDP_ROLLOUT_LAMBDA),
        "pymdp_ensemble_K": int(PYMDP_ENSEMBLE_K),
        "pymdp_ensemble_coupling_lambda": float(PYMDP_ENSEMBLE_COUPLING_LAMBDA),
        "pymdp_ensemble_gamma": float(PYMDP_ENSEMBLE_GAMMA),
        "pymdp_sweep_observations": list(PYMDP_SWEEP_OBSERVATIONS),
        "pymdp_agent_policy_len": int(PYMDP_AGENT_POLICY_LEN),
        "pymdp_agent_inference_algo": str(PYMDP_AGENT_INFERENCE_ALGO),
        "pymdp_agent_num_iter": int(PYMDP_AGENT_NUM_ITER),
        "pymdp_agent_action_selection": str(PYMDP_AGENT_ACTION_SELECTION),
        "pymdp_agent_alpha": float(PYMDP_AGENT_ALPHA),
        "pymdp_agent_use_states_info_gain": bool(PYMDP_AGENT_USE_STATES_INFO_GAIN),
        "pymdp_agent_use_param_info_gain": bool(PYMDP_AGENT_USE_PARAM_INFO_GAIN),
        # global
        "figure_global_seed": int(FIGURE_GLOBAL_SEED),
        "tt_rank_profile_lambda": float(TT_RANK_PROFILE_LAMBDA),
        "spectral_rank_atol": float(SPECTRAL_RANK_ATOL),
        "joint_heatmap_lambda": float(JOINT_HEATMAP_LAMBDA),
        "archetype_dendrogram_lambda": float(ARCHETYPE_DENDROGRAM_LAMBDA),
        "montecarlo_mi_lambda": float(MONTECARLO_MI_LAMBDA),
        "montecarlo_mi_n": int(MONTECARLO_MI_N),
        "montecarlo_mi_seeds": int(MONTECARLO_MI_SEEDS),
        "montecarlo_mi_bias_tol": float(MONTECARLO_MI_BIAS_TOL),
        "coupling_graph_stream_count": int(COUPLING_GRAPH_STREAM_COUNT),
        "bernoulli_verification_tolerance": float(BERNOULLI_VERIFICATION_TOLERANCE),
        "param_sweep_agreement_tolerance": float(PARAMETER_SWEEP_AGREEMENT_TOLERANCE),
        "pymdp_marginal_agreement_tolerance": float(PYMDP_MARGINAL_AGREEMENT_TOLERANCE),
        "pymdp_tc_zero_tolerance": float(PYMDP_TC_ZERO_TOLERANCE),
        "pymdp_coupling_zero_tolerance": float(PYMDP_COUPLING_ZERO_TOLERANCE),
        "pymdp_entropy_add_tolerance": float(PYMDP_ENTROPY_ADD_TOLERANCE),
        "pymdp_decomposition_residual_tolerance": float(PYMDP_DECOMPOSITION_RESIDUAL_TOLERANCE),
        "pymdp_single_stream_float_tolerance": float(PYMDP_SINGLE_STREAM_FLOAT_TOLERANCE),
        "phase_lambda_c1": float(PHASE_LAMBDA_C1),
        "phase_lambda_c2": float(PHASE_LAMBDA_C2),
        "coupling_tax_probe_lambda": float(COUPLING_TAX_PROBE_LAMBDA),
        # multi-K, long-horizon, revertibility
        "multi_k_values": list(int(k) for k in MULTI_K_VALUES),
        "multi_k_sweep_grid_points": grid_count(MULTI_K_SWEEP_LAMBDAS),
        "multi_k_sweep_lambda_min": float(MULTI_K_SWEEP_LAMBDAS.start),
        "multi_k_sweep_lambda_max": float(MULTI_K_SWEEP_LAMBDAS.stop),
        "multi_k_sentinel_lambda": float(MULTI_K_SENTINEL_LAMBDA),
        "long_horizon_steps": int(LONG_HORIZON_STEPS),
        "long_horizon_lambda": float(LONG_HORIZON_LAMBDA),
        "long_horizon_seed": int(LONG_HORIZON_SEED),
        "long_horizon_replicate_seeds": list(int(s) for s in LONG_HORIZON_REPLICATE_SEEDS),
        "long_horizon_replicate_seed_count": len(LONG_HORIZON_REPLICATE_SEEDS),
        "long_horizon_tail_window": int(LONG_HORIZON_TAIL_WINDOW),
        "long_horizon_steady_state_tol": float(LONG_HORIZON_STEADY_STATE_TOL),
        "robustness_observation_contexts": [list(obs) for obs in ROBUSTNESS_OBSERVATION_CONTEXTS],
        "robustness_observation_context_count": len(ROBUSTNESS_OBSERVATION_CONTEXTS),
        "robustness_gammas": [float(x) for x in ROBUSTNESS_GAMMAS],
        "robustness_gamma_count": len(ROBUSTNESS_GAMMAS),
        "robustness_preference_strengths": [float(x) for x in ROBUSTNESS_PREFERENCE_STRENGTHS],
        "robustness_preference_strength_count": len(ROBUSTNESS_PREFERENCE_STRENGTHS),
        "robustness_coupling_scales": [float(x) for x in ROBUSTNESS_COUPLING_SCALES],
        "robustness_coupling_scale_count": len(ROBUSTNESS_COUPLING_SCALES),
        "robustness_interaction_families": list(ROBUSTNESS_INTERACTION_FAMILIES),
        "robustness_interaction_family_count": len(ROBUSTNESS_INTERACTION_FAMILIES),
        "robustness_sweep_grid_points": grid_count(ROBUSTNESS_SWEEP_LAMBDAS),
        "robustness_sweep_lambda_min": float(ROBUSTNESS_SWEEP_LAMBDAS.start),
        "robustness_sweep_lambda_max": float(ROBUSTNESS_SWEEP_LAMBDAS.stop),
        "coupling_ablation_variants": list(COUPLING_ABLATION_VARIANTS),
        "coupling_ablation_variant_count": len(COUPLING_ABLATION_VARIANTS),
        "coupling_ablation_kc_matrix": [list(row) for row in COUPLING_ABLATION_KC_MATRIX],
        "long_horizon_diagnostic_thresholds": [float(x) for x in LONG_HORIZON_DIAGNOSTIC_THRESHOLDS],
        "long_horizon_diagnostic_threshold_count": len(LONG_HORIZON_DIAGNOSTIC_THRESHOLDS),
        "revertibility_lambdas": [float(x) for x in REVERTIBILITY_LAMBDAS],
        "revertibility_tolerance": float(REVERTIBILITY_TOLERANCE),
        "revertibility_kl_identity_tolerance": float(REVERTIBILITY_KL_IDENTITY_TOLERANCE),
    }


__all__ = [
    "ADVERSARIAL_DEFAULT_SEED",
    "ADVERSARIAL_EPSILON_GRID",
    "ADVERSARIAL_LAMBDA_GRID",
    "ARCHETYPE_DENDROGRAM_LAMBDA",
    "BERNOULLI_VERIFICATION_LAMBDAS",
    "BERNOULLI_VERIFICATION_TOLERANCE",
    "BTAI_DEFAULT_BUDGETS",
    "BTAI_ENSEMBLE_COUPLING_AMPLITUDE",
    "BTAI_ENSEMBLE_PREFERENCE_STRENGTH",
    "BTAI_HORIZON",
    "BTAI_NUM_STREAMS",
    "BTAI_REFERENCE_LAMBDA",
    "BTAI_UCB_EXPLORATION",
    "COUPLING_ABLATION_KC_MATRIX",
    "COUPLING_ABLATION_VARIANTS",
    "COUPLING_GRAPH_STREAM_COUNT",
    "COUPLING_TAX_LAMBDAS",
    "COUPLING_TAX_PROBE_LAMBDA",
    "FIGURE_GLOBAL_SEED",
    "FigureGrid",
    "ISING_ALIGNMENT_SENTINEL_LAMBDAS",
    "ISING_MI_SATURATION_LAMBDA",
    "ISING_MI_SENTINEL_LAMBDAS",
    "JOINT_HEATMAP_LAMBDA",
    "KL_GEODESIC_LAMBDAS",
    "LAMBDA_STAR_GAMMAS",
    "LAMBDA_STAR_UTILITIES",
    "LOG_WEIGHT_FLOW_LAMBDAS",
    "LONG_HORIZON_DIAGNOSTIC_THRESHOLDS",
    "LONG_HORIZON_LAMBDA",
    "LONG_HORIZON_REPLICATE_SEEDS",
    "LONG_HORIZON_SEED",
    "LONG_HORIZON_STEADY_STATE_TOL",
    "LONG_HORIZON_STEPS",
    "LONG_HORIZON_TAIL_WINDOW",
    "MONTECARLO_MI_BIAS_TOL",
    "MONTECARLO_MI_LAMBDA",
    "MONTECARLO_MI_N",
    "MONTECARLO_MI_SEEDS",
    "MOTOR_ATTENTION_SENTINEL_LAMBDAS",
    "MULTI_K_SENTINEL_LAMBDA",
    "MULTI_K_SWEEP_LAMBDAS",
    "MULTI_K_VALUES",
    "OPTIMAL_LAMBDA_DELTAS",
    "OPTIMAL_LAMBDA_SENTINEL_DELTAS",
    "PARAMETER_SWEEP_AGREEMENT_TOLERANCE",
    "PARAMETER_SWEEP_DEFAULT_UTILITIES",
    "PARAMETER_SWEEP_LAMBDAS",
    "PHASE_DIAGRAM_LAMBDAS",
    "PHASE_LAMBDA_C1",
    "PHASE_LAMBDA_C2",
    "PHASE_LANDSCAPE_LAMBDAS",
    "PHASE_LANDSCAPE_UTILITIES",
    "PYMDP_AGENT_ACTION_SELECTION",
    "PYMDP_AGENT_ALPHA",
    "PYMDP_AGENT_INFERENCE_ALGO",
    "PYMDP_AGENT_NUM_ITER",
    "PYMDP_AGENT_POLICY_LEN",
    "PYMDP_AGENT_USE_PARAM_INFO_GAIN",
    "PYMDP_AGENT_USE_STATES_INFO_GAIN",
    "PYMDP_COUPLING_ZERO_TOLERANCE",
    "PYMDP_DECOMPOSITION_RESIDUAL_TOLERANCE",
    "PYMDP_ENSEMBLE_COUPLING_LAMBDA",
    "PYMDP_ENSEMBLE_GAMMA",
    "PYMDP_ENSEMBLE_K",
    "PYMDP_ENTROPY_ADD_TOLERANCE",
    "PYMDP_MARGINAL_AGREEMENT_TOLERANCE",
    "PYMDP_ROLLOUT_LAMBDA",
    "PYMDP_ROLLOUT_SEED",
    "PYMDP_ROLLOUT_STEPS",
    "PYMDP_SINGLE_STREAM_FLOAT_TOLERANCE",
    "PYMDP_SWEEP_LAMBDAS",
    "PYMDP_SWEEP_OBSERVATIONS",
    "PYMDP_TC_ZERO_TOLERANCE",
    "PYMDP_TOTAL_CORRELATION_SENTINEL_LAMBDAS",
    "REVERTIBILITY_KL_IDENTITY_TOLERANCE",
    "REVERTIBILITY_LAMBDAS",
    "REVERTIBILITY_TOLERANCE",
    "ROBUSTNESS_COUPLING_SCALES",
    "ROBUSTNESS_GAMMAS",
    "ROBUSTNESS_INTERACTION_FAMILIES",
    "ROBUSTNESS_OBSERVATION_CONTEXTS",
    "ROBUSTNESS_PREFERENCE_STRENGTHS",
    "ROBUSTNESS_SWEEP_LAMBDAS",
    "SCHMIDT_RANK_LAMBDAS",
    "SPECTRAL_RANK_ATOL",
    "SPECTRAL_SENTINEL_LAMBDAS",
    "TT_RANK_PROFILE_LAMBDA",
    "TT_RANK_STREAM_COUNTS",
    "figure_hyperparameter_summary",
    "grid_count",
]
