"""Pipeline output manifest writer."""

from __future__ import annotations

import hashlib
import time
from pathlib import Path
from typing import TypedDict, cast

_SHA256_MAX_BYTES = 8 * 1024 * 1024  # 8 MB
_MANIFEST_EXCLUDED_FILENAMES = frozenset({"MANIFEST.md", ".DS_Store"})


class StageSummary(TypedDict):
    script: str
    duration_s: float
    returncode: int


def write_manifest(*, project_root: Path, run_summary: dict[str, object]) -> Path:
    """Emit ``output/MANIFEST.md`` listing every artifact and stage timing."""
    output_dir = project_root / "output"
    manifest_path = output_dir / "MANIFEST.md"
    output_dir.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    lines.append("# Pipeline output manifest")
    lines.append("")
    lines.append(f"*Auto-generated by `scripts/run_all.py` at {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}.*")
    lines.append("")
    lines.append("## Stage timings")
    lines.append("")
    lines.append("| Stage | Wall time (s) | Status |")
    lines.append("|---|---:|---|")
    stages = cast(list[StageSummary], run_summary.get("stages", []))
    for stage in stages:
        lines.append(
            f"| `{stage['script']}` | {stage['duration_s']:.2f} | {'OK' if stage['returncode'] == 0 else 'FAIL'} |"
        )
    lines.append("")
    total = float(run_summary.get("total_wall_s", 0.0))  # type: ignore[arg-type]
    lines.append(f"**Total wall-clock**: {total:.2f}s")
    lines.append("")
    lines.append("## Artifacts")
    lines.append("")
    lines.append(
        "*Round-5 P3-2 addition*: SHA-256 columns enable a "
        "*re-run-and-bit-match* determinism audit.  Files larger than "
        f"{_SHA256_MAX_BYTES // (1024 * 1024)} MB list size only "
        "(checksumming them would dominate the manifest write)."
    )
    lines.append("")
    lines.append("| Path | Size (bytes) | SHA-256 |")
    lines.append("|---|---:|---|")
    for path in sorted(output_dir.rglob("*")):
        if not path.is_file():
            continue
        if path.name in _MANIFEST_EXCLUDED_FILENAMES:
            continue
        try:
            size = path.stat().st_size
        except OSError:
            continue
        rel = path.relative_to(project_root)
        if size <= _SHA256_MAX_BYTES:
            try:
                hasher = hashlib.sha256()
                with path.open("rb") as fh:
                    for chunk in iter(lambda: fh.read(1 << 16), b""):
                        hasher.update(chunk)
                digest = hasher.hexdigest()
            except OSError:
                digest = "(unreadable)"
        else:
            digest = "(skipped: >8 MB)"
        lines.append(f"| `{rel.as_posix()}` | {size} | `{digest}` |")
    manifest_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return manifest_path
