"""Reviewer-facing release-readiness summary — orchestrator facade."""

from __future__ import annotations

import time
from pathlib import Path

from manuscript.readiness_audit import (
    FORBIDDEN_MATHLIB_LOCAL_TOKENS,
    MANIFEST_STAGE_RE,
    MANIFEST_TOTAL_RE,
    subprocess,  # noqa: F401 — test monkeypatch target
)
from manuscript.readiness_audit import (
    as_float as _as_float,
)
from manuscript.readiness_audit import (
    figure_audit as _figure_audit,
)
from manuscript.readiness_audit import (
    format_stage_list as _format_stage_list,
)
from manuscript.readiness_audit import (
    git_status_lines as _git_status_lines,
)
from manuscript.readiness_audit import (
    manifest_stage_timings as _manifest_stage_timings,
)
from manuscript.readiness_audit import (
    mathlib_proofs_status as _mathlib_proofs_status,
)
from manuscript.readiness_audit import (
    optional_json as _optional_json,
)
from manuscript.readiness_audit import (
    pdf_artifact_audit as _pdf_artifact_audit,
)
from manuscript.readiness_audit import (
    reconcile_runtime_budget as _reconcile_runtime_budget,
)
from manuscript.readiness_audit import (
    registered_figure_paths as _registered_figure_paths,
)
from manuscript.readiness_audit import (
    runtime_failed_stage_names as _runtime_failed_stage_names,
)
from manuscript.readiness_audit import (
    runtime_stage_dicts as _runtime_stage_dicts,
)
from manuscript.readiness_audit import (
    status_counts as _status_counts,
)
from manuscript.readiness_audit import (
    theorem_status_counts as _theorem_status_counts,
)
from manuscript.readiness_emit import (
    _write_readiness_json,
    _write_release_index,
    _write_release_note,
)
from manuscript.status import load_project_status


def refresh_release_readiness_runtime_budget(project_root: Path) -> None:
    """Re-sync ``release_readiness.json`` runtime budget from the final manifest."""
    import json

    json_path = project_root / "output" / "reports" / "release_readiness.json"
    if not json_path.exists():
        return
    try:
        payload = json.loads(json_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return
    if not isinstance(payload, dict):
        return
    payload["runtime_budget"] = _manifest_stage_timings(project_root=project_root)
    json_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_release_readiness(project_root: Path) -> Path:
    """Full release-readiness orchestrator; emits all four artifacts."""
    out = project_root / "output" / "reports" / "release_readiness.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    status = load_project_status(project_root)
    git_lines = _git_status_lines(project_root)
    counts = _status_counts(git_lines)
    manifest = project_root / "output" / "MANIFEST.md"
    test_results = _optional_json(project_root / "output" / "reports" / "test_results.json")
    figures = sorted((project_root / "output" / "figures").glob("*.png"))
    generated_manuscript = sorted((project_root / "output" / "manuscript").glob("*.md"))
    release_note = _write_release_note(
        project_root,
        status=status,
        figures=figures,
        generated_manuscript=generated_manuscript,
        manifest_present=manifest.exists(),
    )
    readiness_json = _write_readiness_json(
        project_root,
        status=status,
        figures=figures,
        generated_manuscript=generated_manuscript,
        manifest_present=manifest.exists(),
    )
    release_index = _write_release_index(
        project_root,
        release_note=release_note,
        readiness_json=readiness_json,
        readiness_md=out,
        manifest=manifest,
    )
    test_results = _optional_json(project_root / "output" / "reports" / "test_results.json")
    runtime_budget = _manifest_stage_timings(manifest, project_root=project_root)
    runtime_budget = _reconcile_runtime_budget(runtime_budget, status=status, test_results=test_results)
    mathlib_status = _mathlib_proofs_status(project_root, runtime_budget)
    figure_audit = _figure_audit(project_root, figures)
    missing_figures = figure_audit.get("missing_registered_figures", [])
    missing_figure_count = len(missing_figures) if isinstance(missing_figures, list) else 0

    lines = [
        "# Release Readiness Report",
        "",
        f"*Generated by `scripts/readiness_report.py` at {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}.*",
        "",
        "## Live Gate Snapshot",
        "",
        f"- Pytest: {status.test_summary}.",
        f"- Coverage: {status.coverage_percent:.2f}%.",
        f"- Combined PDF: {status.pdf_summary}.",
        f"- PNG figures present: {len(figures)}.",
        f"- Rendered manuscript markdown files: {len(generated_manuscript)}.",
        f"- Pipeline manifest: {'present' if manifest.exists() else 'missing'}.",
        f"- Reviewer release note: `{release_note.relative_to(project_root)}`.",
        f"- Machine-readable readiness JSON: `{readiness_json.relative_to(project_root)}`.",
        f"- Reviewer release index: `{release_index.relative_to(project_root)}`.",
    ]
    if test_results:
        project = test_results.get("project")
        if isinstance(project, dict):
            lines.append("- Regression JSON loaded from `output/reports/test_results.json`.")
    lines.extend(
        [
            "",
            "## Optional MathlibProofs Gate",
            "",
            f"- Source present: {bool(mathlib_status['present'])}.",
            f"- Build checked in latest manifest: {bool(mathlib_status['build_checked'])}.",
            f"- Latest manifest status: {mathlib_status['build_status']}.",
            f"- proofSliceVersion: {mathlib_status['proofSliceVersion']}.",
            f"- Local theorem declarations: {mathlib_status['theorem_count']}.",
            f"- Local hygiene clean: {bool(mathlib_status['hygiene_clean'])}.",
            "- Claim status: separate Mathlib package; headline real-valued decomposition discharged when keystone build and axiom audit pass; remaining witness rows still require row-specific proofs.",
            "",
            "## Runtime Budget",
            "",
            (
                f"- Manifest total wall-clock: {_as_float(runtime_budget.get('total_wall_s')):.2f}s."
                if runtime_budget.get("total_wall_s") is not None
                else "- Manifest total wall-clock: unavailable."
            ),
            f"- Stages recorded: {runtime_budget['stage_count']}.",
            f"- Failed stages: {', '.join(_runtime_failed_stage_names(runtime_budget)) or 'none'}.",
            f"- Slowest stages: {_format_stage_list(_runtime_stage_dicts(runtime_budget, 'slowest_stages')) or 'unavailable'}.",
            "",
            "## PDF and Figure Audit",
            "",
            f"- Registered figures: {figure_audit['registered_figures']}.",
            f"- PNG figures present: {figure_audit['png_figures']}.",
            f"- PNGs with project metadata: {figure_audit['project_metadata_count']}.",
            f"- PNGs with schema-v2 figure statistics: {figure_audit['schema_v2_metadata_count']}.",
            f"- Missing registered figures: {missing_figure_count}.",
            "",
            "## Worktree Review Slices",
            "",
            "| Slice | Path families | Review intent |",
            "|---|---|---|",
            "| Manuscript and docs | `manuscript/`, `docs/`, `README.md`, `AGENTS.md` | Prose, citation, injection, and reader-map review. |",
            "| Lean boundary | `lean/ActinfPolicyEntanglement/`, `lean/FepSketches/` | Boundary hygiene and theorem/witness coherence. |",
            "| MathlibProofs analytic layer | `lean/MathlibProofs/` | Separate release-path package for the headline real-valued decomposition and future row-specific witness payloads. |",
            "| Simulation and visualization | `src/simulation/`, `src/visualizations/`, `scripts/simulate_*`, figure scripts | Numerical methods, metadata, and generated artifact provenance. |",
            "| Validators and tests | `src/manuscript/`, `scripts/validate_*`, `tests/` | Drift gates and regression coverage. |",
            "",
            "## Current Worktree Summary",
            "",
            f"- Modified: {counts['modified']}",
            f"- Added: {counts['added']}",
            f"- Deleted: {counts['deleted']}",
            f"- Untracked: {counts['untracked']}",
            f"- Other: {counts['other']}",
            "",
            "This report does not stage or commit files. It exists so reviewers can audit the latest local state after the release gates run.",
            "",
        ]
    )
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


__all__ = [
    "FORBIDDEN_MATHLIB_LOCAL_TOKENS",
    "MANIFEST_STAGE_RE",
    "MANIFEST_TOTAL_RE",
    "_status_counts",
    "_as_float",
    "_runtime_stage_dicts",
    "_runtime_failed_stage_names",
    "_format_stage_list",
    "_optional_json",
    "_git_status_lines",
    "_theorem_status_counts",
    "_manifest_stage_timings",
    "_mathlib_proofs_status",
    "_registered_figure_paths",
    "_figure_audit",
    "_pdf_artifact_audit",
    "_write_release_note",
    "_write_readiness_json",
    "_write_release_index",
    "refresh_release_readiness_runtime_budget",
    "subprocess",
    "write_release_readiness",
]
