"""Release-readiness artifact writers.

Emits reviewer-facing markdown/JSON/index files. Helpers live in
:mod:`manuscript.readiness`; this module avoids circular imports by
importing them lazily inside each writer.
"""

from __future__ import annotations

import json
import time
from pathlib import Path


def _write_release_note(
    project_root: Path,
    *,
    status,
    figures: list[Path],
    generated_manuscript: list[Path],
    manifest_present: bool,
    out_dir: Path | None = None,
) -> Path:
    """Write a compact reviewer release note from live artifacts."""
    from manuscript.readiness import (
        _as_float,
        _format_stage_list,
        _manifest_stage_timings,
        _mathlib_proofs_status,
        _runtime_stage_dicts,
        _theorem_status_counts,
    )

    report_dir = out_dir or project_root / "output" / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    out = report_dir / "release_note.md"
    theorem_counts = _theorem_status_counts(project_root)
    sidecars = sorted((project_root / "output" / "simulations").glob("*.csv"))
    runtime_budget = _manifest_stage_timings(project_root=project_root)
    mathlib_status = _mathlib_proofs_status(project_root, runtime_budget)
    slowest_text = _format_stage_list(_runtime_stage_dicts(runtime_budget, "slowest_stages"))
    lines = [
        "# Reviewer Release Note",
        "",
        f"*Generated by `scripts/readiness_report.py` at {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}.*",
        "",
        "## Live Snapshot",
        "",
        f"- Pytest: {status.test_summary}; coverage {status.coverage_percent:.2f}%.",
        f"- Combined PDF: {status.pdf_summary}.",
        f"- PNG figures: {len(figures)}.",
        f"- Simulation CSV sidecars: {len(sidecars)}.",
        f"- Rendered manuscript markdown files: {len(generated_manuscript)}.",
        f"- Pipeline manifest: {'present' if manifest_present else 'missing'}.",
        "",
        "## Claim Strength Ledger",
        "",
        "| Strength | Meaning in this release |",
        "|---|---|",
        "| `proved` | Machine-checked as the registered boundary statement; per-row `faithfulness:` determines whether it is substantive or statement-restricted. |",
        "| `boundary` | Typed boundary row: either a definitional boundary fact or a witness-threaded contract. |",
        "| `witness` | Typed Lean witness record exists; analytic payload remains supplied externally. |",
        "| `empirical` | Generated from scripts and validated by CSV/JSON/PNG gates. |",
        "| `hypothesis` | Interpretive or biological/clinical framing; not a theorem or benchmark claim. |",
        "| `roadmap` | Planned additive work, including separate Mathlib witness discharge. |",
        "",
        "## Theorem Registry",
        "",
        (
            f"- Total rows: {theorem_counts['total']} "
            f"({theorem_counts['proved']} proved, {theorem_counts['witness']} witness, "
            f"{theorem_counts['boundary']} boundary, {theorem_counts['forwarder']} forwarder, "
            f"{theorem_counts['sketch']} sketch, {theorem_counts['deferred']} deferred)."
        ),
        "",
        "## MathlibProofs Scope",
        "",
        (
            "- Optional package source is present at `lean/MathlibProofs/MathlibProofs.lean`; "
            f"proofSliceVersion={mathlib_status['proofSliceVersion']}, "
            f"{mathlib_status['theorem_count']} theorem declarations, "
            f"latest manifest status: {mathlib_status['build_status']}. "
            "The package validates separate Mathlib plumbing but does not promote any manuscript theorem row."
            if mathlib_status["present"]
            else "- Optional MathlibProofs source is not present."
        ),
        "",
        "## Runtime Budget",
        "",
        (
            f"- Latest manifest total wall time: {_as_float(runtime_budget.get('total_wall_s')):.2f}s."
            if runtime_budget.get("total_wall_s") is not None
            else "- Latest manifest total wall time: unavailable."
        ),
        f"- Slowest stages: {slowest_text or 'unavailable'}.",
        "",
        "## Empirical Stress Evidence",
        "",
        "- One-axis robustness, fixed coupling ablations, targeted two-axis interactions, and long-horizon seed diagnostics are appendix/supporting evidence.",
        "- Long-horizon replicate variability is retained as sensitivity evidence rather than tuned away.",
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def _write_readiness_json(
    project_root: Path,
    *,
    status,
    figures: list[Path],
    generated_manuscript: list[Path],
    manifest_present: bool,
    out_dir: Path | None = None,
) -> Path:
    """Write a machine-readable readiness summary from live artifacts."""
    from manuscript.readiness import (
        _figure_audit,
        _manifest_stage_timings,
        _mathlib_proofs_status,
        _optional_json,
        _pdf_artifact_audit,
        _reconcile_runtime_budget,
        _theorem_status_counts,
    )

    report_dir = out_dir or project_root / "output" / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    out = report_dir / "release_readiness.json"
    sidecars = sorted((project_root / "output" / "simulations").glob("*.csv"))
    runtime_budget = _manifest_stage_timings(project_root=project_root)
    mathlib_status = _mathlib_proofs_status(project_root, runtime_budget)
    figure_audit = _figure_audit(project_root, figures)
    pdf_audit = _pdf_artifact_audit(project_root, status)
    test_results = _optional_json(project_root / "output" / "reports" / "test_results.json")
    runtime_budget = _reconcile_runtime_budget(runtime_budget, status=status, test_results=test_results)
    payload = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "generated_by": "scripts/readiness_report.py",
        "tests": {
            "total": int(status.tests_total),
            "passed": int(status.tests_passed),
            "skipped": int(status.tests_skipped),
            "failed": int(status.tests_failed),
            "summary": status.test_summary,
        },
        "coverage": {
            "percent": float(status.coverage_percent),
        },
        "pdf": {
            "pages": int(status.pdf_pages),
            "size_bytes": int(status.pdf_size_bytes),
            "size_mb": float(status.pdf_size_mb),
            "summary": status.pdf_summary,
        },
        "artifacts": {
            "png_figures": len(figures),
            "rendered_manuscript_markdown": len(generated_manuscript),
            "simulation_csv_sidecars": len(sidecars),
            "pipeline_manifest_present": bool(manifest_present),
        },
        "theorems": _theorem_status_counts(project_root),
        "mathlib_proofs": mathlib_status,
        "runtime_budget": runtime_budget,
        "figure_audit": figure_audit,
        "pdf_audit": pdf_audit,
    }
    out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return out


def _write_release_index(
    project_root: Path,
    *,
    release_note: Path,
    readiness_json: Path,
    readiness_md: Path,
    manifest: Path,
    out_dir: Path | None = None,
) -> Path:
    """Write a tiny reviewer landing page linking generated release artifacts."""

    report_dir = out_dir or project_root / "output" / "reports"
    report_dir.mkdir(parents=True, exist_ok=True)
    out = report_dir / "release_index.md"

    def _rel(path: Path) -> str:
        try:
            return path.relative_to(project_root).as_posix()
        except ValueError:
            return path.as_posix()

    rows = [
        ("Release readiness report", readiness_md),
        ("Machine-readable readiness JSON", readiness_json),
        ("Reviewer release note", release_note),
        ("Pipeline manifest", manifest),
        ("Theorem map", project_root / "docs" / "reference" / "_theorem_map.md"),
        ("Combined PDF", project_root / "output" / "pdf" / "actinf_policy_entanglement_lean_combined.pdf"),
    ]
    lines = [
        "# Reviewer Release Index",
        "",
        f"*Generated by `scripts/readiness_report.py` at {time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}.*",
        "",
        "| Artifact | Path |",
        "|---|---|",
    ]
    for label, path in rows:
        lines.append(f"| {label} | `{_rel(path)}` |")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


__all__ = [
    "_write_release_note",
    "_write_readiness_json",
    "_write_release_index",
]
